### ISSUE TITLE
The plugin does not work with a shared prettier config

### ISSUE THREAD

**Issue by Cry0nicS** [tailwindlabs/prettier-plugin-tailwindcss#217]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.5.4

**What version of Tailwind CSS are you using?**

v3.3.3

**What version of Node.js are you using?**

v20.6.1

**What package manager are you using?**

npm

**What operating system are you using?**

Windows 11 (same on MacOS tho)

**Reproduction URL**

https://github.com/Cry0nicS/prettier-config-test

**Describe your issue**

[prettier-plugin-tailwindcss](https://github.com/tailwindlabs/prettier-plugin-tailwindcss) does not work when using a shared prettier config.

Check out the reproduction URL. Run `npm run format-check`. It should highlight that 
```vue
// app.vue
<h1 class="underline text-3xl font-bold">Hello world!</h1>
```
the classes are not in the right order (`underline` should be last).

I've used a shared config that is public. And that works correctly. To test, introduce some spaces or whatever. Like
```vue
// app.vue
<h1 class="underline text-3xl font-bold"   >    Hello world!</h1>
```
and run the same command `npm run format-check` .

Note: I've added the shared config to `package.json`, since I could not add it to the `prettier.config.js` - as `require` is not allowed anymore.

Removing the shared prettier config (just remove line 23 in `package.json`) will enable prettier-plugin-tailwindcss. As a result prettier will format the same code to  the following (notice the order of the classes)
```vue
<template>
  <div>
    <h1 class="text-3xl font-bold underline">Hello world!</h1>
  </div>
</template>
```

**Comment by thecrypticace** [comment]
This is because the configuration in `package.json` is taking precedence over the `prettier.config.js` file and thus no plugins are specified.

You _can_ use require in `prettier.config.js`. You just can't use it to load `prettier-plugin-tailwindcss` or any other plugin or package that is ESM-only.

Remove the `prettier` line from your package.json and replace your `prettier.config.js` with this:
```
const baseConfig = require('@magister_zito/prettier-config')

module.exports = {
  ...baseConfig,
  plugins: ['prettier-plugin-tailwindcss'],
}
```

This should work — I tested it myself and it appears to work fine.

**Comment by Cry0nicS** [comment]
@thecrypticace thanks for looking into this.

I've tried that too. And it does seem to work, however I started running into the following
```
    Error: require() of ES Module C:\Programming\prettier-config-test\node_modules\prettier-plugin-tailwindcss\dist\index.mjs not supported.
    Instead change the require of C:\Programming\prettier-config-test\nuxt-prototype\node_modules\prettier-plugin-tailwindcss\dist\index.mjs to a dynamic import() which is available in   
    all CommonJS modules.
    Code: ERR_REQUIRE_ESM

```

**Comment by thecrypticace** [comment]
@Cry0nicS that would mean something is calling `require()` with the prettier plugin itself (which you can't do). Can you provide a reproduction?

**Comment by thecrypticace** [comment]
I'm not worried about it being a minimal repro btw — is it the `nuxt-prototype` repo [here](https://github.com/Cry0nicS/nuxt-prototype)?

**Comment by Cry0nicS** [comment]
@thecrypticace  Not really sure how to share a reproduction as it is influenced by a script running locally.

I've tried to make a video, maybe it help? Here:
![phpstorm64_FJ3xKpGvcL](https://github.com/tailwindlabs/prettier-plugin-tailwindcss/assets/29982205/d2bc967d-4f92-49c4-8d5c-0272adbef993)


Basically, in the `nuxt-prototype` project (exactly as you see it, nothing changed), [I run this script to generate](https://github.com/Contentstack-Solutions/contentstack-cli-tsgen) some Typescript types. This is just some CLI that runs on my machine.

First time, I'm running it without the prettier-plugin-tailwindcss and it works. It just creates a `types` folder with some TS types.
Second time, I've added the plugin. Just as you mentioned.

And now it throws this error. I can generate those types anywhere, should have really 0 impact on the project. If I set the output folder outside of the project... it works again.

Not sure if it makes any sense 🙈 But I figured it was related to the plugin, as the error does not occure in any other folder that doesn't run prettier-plugin-tailwindcss.

**Comment by Cry0nicS** [comment]
That's amazing. Will try out. Either way, now I understand the issue.

Thanks a lot!

**Comment by Cry0nicS** [comment]
@thecrypticace just as a FYI, in my particular case, it was basically enough to do this:
```js
const baseConfig = require('@magister_zito/prettier-config')

module.exports = {
  ...baseConfig,
  overrides: [
    {
      files: ["**/**"],
      options: {
        plugins: ["prettier-plugin-tailwindcss"]
      },
    },
  ],
}

```

Now everything works as expected.

Thanks again for the idea!

**Comment by cumt-robin** [comment]
but after I upgraded Prettier to v3, another problem occurred when i ran eslint.
TypeError: prettier.resolveConfig.sync is not a function

**Comment by cumt-robin** [comment]
> TypeError: prettier.resolveConfig.sync is not a function
// update the version, it works.
"eslint-plugin-prettier": "^5.2.1",
