### ISSUE TITLE
Error: Cannot find module '@tailwindcss/forms'

### ISSUE THREAD

**Issue by cungminh2710** [tailwindlabs/prettier-plugin-tailwindcss#82]
**What version of `prettier-plugin-tailwindcss` are you using?**

v0.1.11

**What version of Tailwind CSS are you using?**

v3.0.22

**What version of Node.js are you using?**

v16

**What package manager are you using?**

Yarn

**What operating system are you using?**

Linux

**Reproduction**
```
name: Code Format

on: workflow_dispatch

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}
          # This is important to fetch the changes to the previous commit
          fetch-depth: 0

      - name: Prettify code
        uses: creyD/prettier_action@v4.2
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/*.{js,ts,tsx} --print-width 120 --use-tabs --single-quote --jsx-single-quote
          prettier_plugins: "prettier-plugin-tailwindcss@0.1.11"
```

**Describe your issue**

After upgrading from v0.1.4 -> v0.1.11, we are facing this issue when using with `creyD/prettier_action`

![image](https://user-images.githubusercontent.com/8063319/173711824-b5d5cc85-5254-43f0-aa46-594603e21b98.png)

**Comment by bradlc** [comment]
@cungminh2710 Please can you provide a public GitHub repo that includes a minimal reproduction of the bug? **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways. Unfortunately we won't be able to debug the issue without a reproduction. Thanks!

**Comment by manavm1990** [comment]
Seems to be more of an issue on the `creyD/prettier_action` side of things. It's probably outside of the scope of `prettier` functionality. However, I am just guessing.

There is normally no issue with using the Tailwind form plugin 🔌  and alongside this prettier plugin.

**Comment by devanshkaloti** [comment]
Had this same problem without using `creyD/prettier_action`. 
We fixed it by changing `plugins: ["@tailwindcss/forms"],` to  `plugins: ["@tailwindcss/forms"],` in `tailwind.config.js`. 

Not sure yet if it is the right approach, but it's working now.
